# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: SDKs

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        version:
          - "16.0"
          - "15.0"
          - "14.0"
          - "13.0"
          - "12.0"

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install blacktop/ipsw                             # Blacktop's brew tap doesn't support Linux currently
      run: |
        git clone https://github.com/blacktop/ipsw
        cd ipsw
        curl -L https://github.com/blacktop/ipsw/releases/latest/download/ipsw_"$(git describe --tags $(git rev-list --tags --max-count=1) | cut -c2-)"_linux_x86_64.deb -o ipsw.deb
        sudo dpkg -i ipsw.deb

    - name: Install apfs-fuse
      run: |
        sudo apt update && sudo apt install -y libfuse3-dev
        git clone --recursive https://github.com/sgan81/apfs-fuse
        cd apfs-fuse
        mkdir build && cd build
        cmake ../
        make -j$(nproc --all) install

    - name: Set up python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install progressbar2 dyldextractor poetry
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        git clone https://github.com/cxnder/ktool.git && cd ktool && chmod +x dev_install.sh && ./dev_install.sh

    - name: Build SDK
      run: |
        python3 sdkgen.py ${{ matrix.version }}

    - name: Prep SDK for artifact upload
      run: |
        mv ${{ matrix.version }}.extracted iPhoneOS${{ matrix.version }}.sdk
        zip -9 -r iPhoneOS${{ matrix.version }}.sdk.zip iPhoneOS${{ matrix.version }}.sdk

    - name: Upload SDK artifact
      uses: actions/upload-artifact@main
      with:
        name: ${{ matrix.version }}
        path: iPhoneOS${{ matrix.version }}.sdk.zip
